import type { Metadata } from "next";
import "./globals.css";

// ** Toast
import { Toaster } from 'react-hot-toast';
import Navbar from "@/app/components/nav/(page)/Navbar";
import Footer from "@/app/components/footer/(page)/Footer";
import { useEffect, useState } from "react";
import SubNavbar from "./components/subNav/(page)/SubNavbar";
import CartProvider from "@/providers/CartProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="fa" dir="rtl">
      <body className="text-slate-700">
        <Toaster toastOptions={{
          style: {
            background: 'rgb(51 65 85)',
            color: '#fff',
          },
        }} />
        <CartProvider>
          <div className="flex flex-col min-h-screen">
            <Navbar />
            <main className="flex-grow">
              {children}
            </main>
            <Footer />
          </div>
        </CartProvider>
      </body>
    </html>
  );
}
